#!/usr/bin/env python3
"""
Generates signal_catalog_autogen.h: a named, typed, read-only catalog of
every IN/OUT/CFG/STATE signal across the controller modules wired into
ieee_cigre_dll/gfm_battery_app.c (resolved by scanning that file's
'#include "..._autogen.h"' lines, so mutually-exclusive schema variants
like current_limiting_A/current_limiting_B never collide).

Each entry keeps a human-readable name (e.g. "acMonitor_OUT.frequency",
matching what a user types into debug_signals_config.yaml and what
becomes a COMTRADE channel label) alongside a typed pointer into the live
global struct. Bool signals are included, for use as COMTRADE digital
channels.

Also emits available_signals_autogen.txt (one signal name per line) so a
user can copy-paste valid names into debug_signals_config.yaml instead of
guessing.

Usage: python generate_signal_catalog.py [target_c_path] [schema_root] [output_header] [output_root]
    target_c_path defaults to ../gfm_battery_app.c
    schema_root defaults to ../../c_language_library (searched recursively for *_schema.yaml)
    output_header defaults to signal_catalog_autogen.h next to this script
    output_root is the directory #include paths are computed relative to,
        and where available_signals_autogen.txt is written (defaults to
        output_header's directory)
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
DLL_DIR = os.path.dirname(SCRIPT_DIR)
SCHEMA_TOOLS_DIR = os.path.join(REPO_ROOT, 'schema_tools')
sys.path.insert(0, SCHEMA_TOOLS_DIR)

from generate_header import SchemaParser
from schema_signal_utils import (
    expand_signal,
    get_active_schema_files,
    get_autogen_include_path,
)

# Maps a YAML scalar type (cmplx_t is pre-resolved to 'float' by the caller,
# since its REAL/IMAG components are plain floats) to the catalog enum/union.
TYPE_ENUM = {
    'float': 'SIGNAL_CATALOG_TYPE_FLOAT',
    'bool':  'SIGNAL_CATALOG_TYPE_BOOL',
    'int':   'SIGNAL_CATALOG_TYPE_INT',
    'uint':  'SIGNAL_CATALOG_TYPE_UINT',
}
UNION_FIELD = {
    'float': 'f',
    'bool':  'b',
    'int':   'i',
    'uint':  'u',
}


def _escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def collect_catalog_rows(schema_path: str) -> list:
    """Return (name, unit, catalog_type, access_expr) tuples for every signal
    in every group of a schema file, including bool signals."""
    parser = SchemaParser(schema_path)
    module_name = parser.get_module_name()

    rows = []
    for group_name, group_data in parser.get_groups().items():
        if not isinstance(group_data, dict) or 'signals' not in group_data:
            continue

        struct_instance = f"{module_name}_{group_name}"
        signals = group_data.get('signals', {})

        for signal_name, signal_def in signals.items():
            if not isinstance(signal_def, dict) or 'type' not in signal_def:
                continue

            yaml_type = signal_def['type']
            if yaml_type not in ('float', 'bool', 'int', 'uint', 'cmplx_t'):
                continue

            catalog_type = 'float' if yaml_type == 'cmplx_t' else yaml_type
            unit = signal_def.get('units', '') or ''

            for _id_suffix, access_expr in expand_signal(signal_name, signal_def):
                name = f"{struct_instance}.{access_expr}"
                rows.append((name, unit, catalog_type, f"{struct_instance}.{access_expr}"))

    return rows


def generate(target_c_path: str, schema_root: str, output_header: str, output_root: str):
    schema_files = get_active_schema_files(target_c_path, schema_root)

    includes = []
    all_rows = []
    for schema_path in schema_files:
        includes.append(get_autogen_include_path(schema_path, output_root).replace(os.sep, '/'))
        all_rows.extend(collect_catalog_rows(schema_path))

    # de-duplicate by name while preserving order, in case two schemas collide
    seen = set()
    unique_rows = []
    for name, unit, catalog_type, access_expr in all_rows:
        if name not in seen:
            seen.add(name)
            unique_rows.append((name, unit, catalog_type, access_expr))

    lines = [
        "#ifndef SIGNAL_CATALOG_AUTOGEN_H",
        "#define SIGNAL_CATALOG_AUTOGEN_H",
        "",
        "// Auto-generated by generate_signal_catalog.py -- do not edit by hand",
        "",
        '#include "signal_catalog.h"',
    ]
    for include in includes:
        lines.append(f'#include "{include}"')

    lines += [
        "",
        "const SignalCatalogEntry g_signalCatalog[] = {",
    ]
    for name, unit, catalog_type, access_expr in unique_rows:
        enum_name = TYPE_ENUM[catalog_type]
        union_field = UNION_FIELD[catalog_type]
        lines.append(
            f'    {{ "{_escape(name)}", "{_escape(unit)}", {enum_name}, {{ .{union_field} = &{access_expr} }} }},'
        )
    lines += [
        "};",
        "const int g_signalCatalogCount = sizeof(g_signalCatalog) / sizeof(g_signalCatalog[0]);",
        "",
        "#endif // SIGNAL_CATALOG_AUTOGEN_H",
        "",
    ]

    with open(output_header, 'w') as f:
        f.write("\n".join(lines))

    print(f"Successfully generated {output_header} ({len(unique_rows)} signals from {len(schema_files)} active modules)")

    txt_path = os.path.join(output_root, 'available_signals_autogen.txt')
    with open(txt_path, 'w') as f:
        for name, unit, _catalog_type, _access_expr in unique_rows:
            f.write(f"{name}" + (f"  [{unit}]" if unit else "") + "\n")

    print(f"Successfully generated {txt_path}")


def main():
    default_target_c = os.path.join(DLL_DIR, 'gfm_battery_app.c')
    default_root = os.path.join(REPO_ROOT, 'c_language_library')
    default_output = os.path.join(SCRIPT_DIR, 'signal_catalog_autogen.h')

    target_c_path = sys.argv[1] if len(sys.argv) > 1 else default_target_c
    schema_root = sys.argv[2] if len(sys.argv) > 2 else default_root
    output_header = sys.argv[3] if len(sys.argv) > 3 else default_output
    output_root = sys.argv[4] if len(sys.argv) > 4 else os.path.dirname(output_header)

    generate(target_c_path, schema_root, output_header, output_root)


if __name__ == "__main__":
    main()
