#!/usr/bin/env python3
"""
Generates extra_outputs_autogen.h: a fixed, compile-time set of extra DLL
output ports exposing internal troubleshooting signals, from
ieee_cigre_dll/debug_signals_config.yaml.

Build-time, not runtime: a DLL's port list must stay stable across a
simulator's whole workflow (e.g. PSCAD's import tool calls Model_GetInfo
once to generate a fixed component definition), so the extra-port list is
baked into the binary rather than read from a file that could change
between import and run.

Reuses generate_signal_catalog.py's schema-scanning/dedup logic so the
emitted g_signalCatalog[] indices line up with signal_catalog_autogen.h.

Output is two C preprocessor macros, expanded in gfm_battery_dll.c:
    EXTRA_OUTPUT_PORT_ROWS       -- spliced inside s_outputPorts[]
    EXTRA_OUTPUT_CATALOG_INDICES -- the s_extraOutputCatalogIndex[] initializer
plus #define NUM_EXTRA_OUTPUT_PORTS.

Usage: python generate_extra_outputs.py [config_path] [target_c_path] [schema_root] [output_header]
    config_path defaults to ../debug_signals_config.yaml
    target_c_path defaults to ../gfm_battery_app.c
    schema_root defaults to ../../c_language_library
    output_header defaults to extra_outputs_autogen.h next to this script
"""

import os
import sys

import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))
DLL_DIR = os.path.dirname(SCRIPT_DIR)

sys.path.insert(0, SCRIPT_DIR)
sys.path.insert(0, os.path.join(REPO_ROOT, 'schema_tools'))

from generate_signal_catalog import collect_catalog_rows
from schema_signal_utils import get_active_schema_files

# Maps a catalog type to the IEEE/CIGRE DataType enum and a display width.
# All our signals are scalar (width 1) once expanded by expand_signal --
# array/cmplx_t signals are already split into per-element scalar rows by
# collect_catalog_rows.
IEEE_DATATYPE = {
    'float': 'IEEE_Cigre_DLLInterface_DataType_real64_T',
    'bool':  'IEEE_Cigre_DLLInterface_DataType_real64_T',
    'int':   'IEEE_Cigre_DLLInterface_DataType_real64_T',
    'uint':  'IEEE_Cigre_DLLInterface_DataType_real64_T',
}


def _escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def read_config(config_path: str) -> list:
    """YAML file with a top-level 'signals:' list of signal names. Returns
    the requested names in file order."""
    with open(config_path, 'r') as f:
        data = yaml.safe_load(f)
    if not data:
        return []
    return list(data.get('signals') or [])


def build_catalog_index(target_c_path: str, schema_root: str) -> dict:
    """Reproduces signal_catalog_autogen.h's exact row order/dedup so the
    indices generated here line up with the real g_signalCatalog[]."""
    schema_files = get_active_schema_files(target_c_path, schema_root)

    all_rows = []
    for schema_path in schema_files:
        all_rows.extend(collect_catalog_rows(schema_path))

    seen = set()
    unique_rows = []
    for row in all_rows:
        name = row[0]
        if name not in seen:
            seen.add(name)
            unique_rows.append(row)

    return {name: (index, unit, catalog_type) for index, (name, unit, catalog_type, _access_expr) in enumerate(unique_rows)}


def generate(config_path: str, target_c_path: str, schema_root: str, output_header: str):
    requested_names = read_config(config_path)
    catalog_index = build_catalog_index(target_c_path, schema_root)

    unmatched = [name for name in requested_names if name not in catalog_index]
    if unmatched:
        sys.stderr.write(
            "ERROR: the following signal(s) in {} do not match any entry in the\n"
            "internal signal catalog (check logging/available_signals_autogen.txt\n"
            "for valid names, generated by generate_signal_catalog.py):\n".format(config_path)
        )
        for name in unmatched:
            sys.stderr.write(f"  {name}\n")
        sys.exit(1)

    row_lines = []
    index_values = []
    for name in requested_names:
        index, unit, catalog_type = catalog_index[name]
        datatype = IEEE_DATATYPE[catalog_type]
        description = f"Diagnostic signal: {name}"
        # IEEE_Cigre_DLLInterface_Signal field order: Name, Description, Unit, DataType, Width
        row_lines.append(
            f'    {{ "{_escape(name)}", "{_escape(description)}", "{_escape(unit)}", {datatype}, 1 }},'
        )
        index_values.append(str(index))

    lines = [
        "#ifndef EXTRA_OUTPUTS_AUTOGEN_H",
        "#define EXTRA_OUTPUTS_AUTOGEN_H",
        "",
        "// Auto-generated by generate_extra_outputs.py from " + os.path.basename(config_path),
        "// -- do not edit by hand",
        "",
        f"#define NUM_EXTRA_OUTPUT_PORTS {len(requested_names)}",
        "",
    ]

    if row_lines:
        lines.append("#define EXTRA_OUTPUT_PORT_ROWS \\")
        lines.extend(f"{row}{'' if i == len(row_lines) - 1 else ' \\'}" for i, row in enumerate(row_lines))
    else:
        lines.append("#define EXTRA_OUTPUT_PORT_ROWS")
    lines.append("")

    lines.append(f"#define EXTRA_OUTPUT_CATALOG_INDICES {{ {', '.join(index_values)} }}")
    lines.append("")
    lines.append("#endif // EXTRA_OUTPUTS_AUTOGEN_H")
    lines.append("")

    with open(output_header, 'w') as f:
        f.write("\n".join(lines))

    print(f"Successfully generated {output_header} ({len(requested_names)} extra output ports from {config_path})")


def main():
    default_config = os.path.join(DLL_DIR, 'debug_signals_config.yaml')
    default_target_c = os.path.join(DLL_DIR, 'gfm_battery_app.c')
    default_root = os.path.join(REPO_ROOT, 'c_language_library')
    default_output = os.path.join(SCRIPT_DIR, 'extra_outputs_autogen.h')

    config_path = sys.argv[1] if len(sys.argv) > 1 else default_config
    target_c_path = sys.argv[2] if len(sys.argv) > 2 else default_target_c
    schema_root = sys.argv[3] if len(sys.argv) > 3 else default_root
    output_header = sys.argv[4] if len(sys.argv) > 4 else default_output

    generate(config_path, target_c_path, schema_root, output_header)


if __name__ == "__main__":
    main()
