/*
 * signal_catalog.h
 *
 * Types for a named, read-only catalog of every IN/OUT/CFG/STATE signal
 * across the controller modules wired into ieee_cigre_dll/gfm_battery_app.c.
 * The catalog data itself (g_signalCatalog[]) is generated by
 * generate_signal_catalog.py into signal_catalog_autogen.h -- this
 * file only declares the stable types/helpers around it.
 *
 * Used to (a) validate debug_signals_config.yaml's requested signal names
 * against what actually exists, and (b) read a signal's current value each
 * timestep for COMTRADE logging, without hand-wiring a pointer/switch per
 * signal.
 */

#ifndef SIGNAL_CATALOG_H
#define SIGNAL_CATALOG_H

#include <stdbool.h>

typedef enum
{
    SIGNAL_CATALOG_TYPE_FLOAT,  /* -> COMTRADE analog channel */
    SIGNAL_CATALOG_TYPE_INT,    /* -> COMTRADE analog channel */
    SIGNAL_CATALOG_TYPE_UINT,   /* -> COMTRADE analog channel */
    SIGNAL_CATALOG_TYPE_BOOL,   /* -> COMTRADE digital channel */
} SignalCatalogType;

typedef struct
{
    const char *name;   /* e.g. "acMonitor_OUT.frequency" -- matches debug_signals_config.yaml entries */
    const char *unit;   /* from the YAML 'units:' field; "" if absent */
    SignalCatalogType type;
    union
    {
        const float        *f;
        const int          *i;
        const unsigned int *u;
        const bool         *b;
    } ptr;
} SignalCatalogEntry;

/* Defined in the generated signal_catalog_autogen.h */
extern const SignalCatalogEntry g_signalCatalog[];
extern const int g_signalCatalogCount;

static inline double signal_catalog_read(const SignalCatalogEntry *entry)
{
    switch (entry->type)
    {
        case SIGNAL_CATALOG_TYPE_FLOAT: return (double)*entry->ptr.f;
        case SIGNAL_CATALOG_TYPE_INT:   return (double)*entry->ptr.i;
        case SIGNAL_CATALOG_TYPE_UINT:  return (double)*entry->ptr.u;
        case SIGNAL_CATALOG_TYPE_BOOL:  return *entry->ptr.b ? 1.0 : 0.0;
        default:                        return 0.0;
    }
}

static inline bool signal_catalog_is_digital(const SignalCatalogEntry *entry)
{
    return entry->type == SIGNAL_CATALOG_TYPE_BOOL;
}

#endif /* SIGNAL_CATALOG_H */
