#!/usr/bin/env python3
"""
Generates the two headers behind the configurable debug DAC:

1. signal_ids_autogen.h -- one #define signal ID per scalar signal (and per
   element of an array signal), across every module app.c actually
   #includes (see the "Only modules app.c actually #includes" note under
   (2) below - the same collision reason applies here: circuit_controls_A
   and circuit_controls_B, for instance, share the schema 'metadata.name'
   circuitControls, so IDs from an unused variant would collide with the
   active one's).

   Naming convention: SIGNAL_ID_<MODULE>_<GROUP>_<SIGNAL>[index]
       e.g. circuitControls.yaml, group OUT, signal i_L (array of 3)
         -> SIGNAL_ID_CIRCUIT_CONTROLS_OUT_IL0
         -> SIGNAL_ID_CIRCUIT_CONTROLS_OUT_IL1
         -> SIGNAL_ID_CIRCUIT_CONTROLS_OUT_IL2

   cmplx_t signals (struct { float real; float imag; }) are split into a
   _REAL and _IMAG signal apiece, e.g. pll_osc (array of 3, cmplx_t):
         -> ..._PLLOSC_REAL0 / ..._PLLOSC_IMAG0 (etc. per element)

2. configurable_dac_switch_autogen.h -- the switch-case lookup used by
   configurable_dac.c to fetch a signal's current value by its SIGNAL_ID.
   For every signal belonging to a module actually compiled into app.c,
   emits one case that returns the live value out of that module's
   autogenerated struct instance, e.g.:

       case SIGNAL_ID_CIRCUIT_CONTROLS_OUT_IL0: return circuitControls_OUT.i_L[0];

   Only modules app.c actually #includes are considered (rather than every
   schema under c_language_library) because some modules share a schema
   'metadata.name' across mutually-exclusive variants -- e.g. current_limiting_A
   and current_limiting_B both define a `currentLimiting_IN` struct, but with
   different members. Only one variant is ever linked into a given app, so
   including both here would produce conflicting struct redefinitions.

The module *_autogen.h headers must be fresh before running this (run
schema_tools/generate_all_headers.py first). Normally all of this is driven
by ../../generate_project_files.py rather than invoked directly.

Usage: python generate_configurable_dac.py [app_c_path] [schema_root] [output_header] [output_root]
    app_c_path defaults to ../app.c
    schema_root defaults to ../../../c_language_library (searched recursively for *_schema.yaml)
    output_header defaults to configurable_dac_switch_autogen.h next to this script
    output_root is the directory the #include paths are computed relative to,
        and where signal_ids_autogen.h is written (defaults to output_header's directory)
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..', '..', '..'))
SCHEMA_TOOLS_DIR = os.path.join(REPO_ROOT, 'schema_tools')
sys.path.insert(0, SCHEMA_TOOLS_DIR)

from generate_header import SchemaParser
from schema_signal_utils import (
    camel_to_snake_upper,
    expand_signal,
    get_active_schema_files,
    get_autogen_include_path,
)


#
# Signal ID header (signal_ids_autogen.h)
#

def collect_signal_ids(schema_path: str) -> list:
    """Return a list of #define names for every signal (and array element) in a schema file."""
    parser = SchemaParser(schema_path)
    module_token = camel_to_snake_upper(parser.get_module_name())

    names = []
    for group_name, group_data in parser.get_groups().items():
        if not isinstance(group_data, dict) or 'signals' not in group_data:
            continue

        group_token = camel_to_snake_upper(group_name)
        signals = group_data.get('signals', {})

        for signal_name, signal_def in signals.items():
            if not isinstance(signal_def, dict) or 'type' not in signal_def:
                continue

            for id_suffix, _ in expand_signal(signal_name, signal_def):
                names.append(f"{module_token}_{group_token}_{id_suffix}")

    return names


def generate_signal_ids_header(schema_files: list, output_header: str):
    all_names = []
    for schema_path in schema_files:
        all_names.extend(collect_signal_ids(schema_path))

    # de-duplicate while preserving order, in case two schemas collide
    seen = set()
    unique_names = []
    for name in all_names:
        if name not in seen:
            seen.add(name)
            unique_names.append(name)

    lines = [
        "#ifndef SIGNAL_IDS_AUTOGEN_H",
        "#define SIGNAL_IDS_AUTOGEN_H",
        "",
        "// Auto-generated by generate_configurable_dac.py -- do not edit by hand",
        "",
    ]
    for i, name in enumerate(unique_names):
        lines.append(f"#define SIGNAL_ID_{name} {i}")
    lines.append("")
    lines.append("#endif // SIGNAL_IDS_AUTOGEN_H")
    lines.append("")

    with open(output_header, 'w') as f:
        f.write("\n".join(lines))

    print(f"Successfully generated {output_header} ({len(unique_names)} signal IDs from {len(schema_files)} schemas)")


#
# Switch-case header (configurable_dac_switch_autogen.h)
#

def collect_switch_cases(schema_path: str) -> list:
    """Return (case_label, struct_expression) pairs for every signal in a schema file."""
    parser = SchemaParser(schema_path)
    module_name = parser.get_module_name()
    module_token = camel_to_snake_upper(module_name)

    cases = []
    for group_name, group_data in parser.get_groups().items():
        if not isinstance(group_data, dict) or 'signals' not in group_data:
            continue

        group_token = camel_to_snake_upper(group_name)
        signals = group_data.get('signals', {})

        for signal_name, signal_def in signals.items():
            if not isinstance(signal_def, dict) or 'type' not in signal_def:
                continue

            # Only scalar/array floats, ints, and cmplx_t (split into real/imag) can drive a DAC value
            if signal_def['type'] not in ('float', 'int', 'uint', 'cmplx_t'):
                continue

            struct_instance = f"{module_name}_{group_name}"

            for id_suffix, access_expr in expand_signal(signal_name, signal_def):
                label = f"SIGNAL_ID_{module_token}_{group_token}_{id_suffix}"
                cases.append((label, f"(float){struct_instance}.{access_expr}"))

    return cases


def generate_switch_header(schema_files: list, output_header: str, output_root: str):
    includes = []
    all_cases = []
    for schema_path in schema_files:
        includes.append(get_autogen_include_path(schema_path, output_root).replace(os.sep, '/'))
        all_cases.extend(collect_switch_cases(schema_path))

    # de-duplicate cases while preserving order, in case two schemas collide
    seen = set()
    unique_cases = []
    for label, expr in all_cases:
        if label not in seen:
            seen.add(label)
            unique_cases.append((label, expr))

    lines = [
        "#ifndef CONFIGURABLE_DAC_SWITCH_AUTOGEN_H",
        "#define CONFIGURABLE_DAC_SWITCH_AUTOGEN_H",
        "",
        "// Auto-generated by generate_configurable_dac.py -- do not edit by hand",
        "",
        '#include "signal_ids_autogen.h"',
    ]
    for include in includes:
        lines.append(f'#include "{include}"')

    lines += [
        "",
        "// Returns the live value of the signal identified by signal_id, or 0.0f if unknown.",
        "static inline float configurable_dac_get_signal_value(int signal_id)",
        "{",
        "    switch (signal_id)",
        "    {",
    ]
    for label, expr in unique_cases:
        lines.append(f"        case {label}: return {expr};")
    lines += [
        "        default: return 0.0f;",
        "    }",
        "}",
        "",
        "#endif // CONFIGURABLE_DAC_SWITCH_AUTOGEN_H",
        "",
    ]

    with open(output_header, 'w') as f:
        f.write("\n".join(lines))

    print(f"Successfully generated {output_header} ({len(unique_cases)} cases from {len(schema_files)} active modules)")


def generate(app_c_path: str, schema_root: str, output_header: str, output_root: str):
    """Generate the signal ID header and the switch-case header, in that order
    (the switch labels must match the IDs). Both are scoped to only the
    modules app_c_path actually #includes (see get_active_schema_files)."""
    schema_files = get_active_schema_files(app_c_path, schema_root)
    generate_signal_ids_header(schema_files, os.path.join(output_root, 'signal_ids_autogen.h'))
    generate_switch_header(schema_files, output_header, output_root)


def main():
    default_app_c = os.path.join(REPO_ROOT, 'demo_projects', 'c_code', 'application', 'app.c')
    default_root = os.path.join(REPO_ROOT, 'c_language_library')
    default_output = os.path.join(SCRIPT_DIR, 'configurable_dac_switch_autogen.h')

    app_c_path = sys.argv[1] if len(sys.argv) > 1 else default_app_c
    schema_root = sys.argv[2] if len(sys.argv) > 2 else default_root
    output_header = sys.argv[3] if len(sys.argv) > 3 else default_output
    output_root = sys.argv[4] if len(sys.argv) > 4 else os.path.dirname(output_header)

    generate(app_c_path, schema_root, output_header, output_root)


if __name__ == "__main__":
    main()
