#!/usr/bin/env python3
"""
Generate dll_config_generated.h from dll_config.yaml.

The YAML sections are flattened into C preprocessor constants:
  advanced_parameters.circuitControls.<name> -> CC_<NAME>_DEFAULT
      Compiled-in circuitControls tuning gains consumed by gfm_battery_app.c.
  exposed_parameters.<name> -> <NAME>_DEFAULT
      Compiled-in defaults for the DLL's real parameters (H, D, and kDroop)
      consumed by gfm_battery_dll.c.

The generated header is named "_generated" rather than "_autogen" so the
schema_tools _autogen.h-include scanner does not try to find a backing schema
file for it.

Usage: python generate_dll_config.py [config_path] [output_header]
    config_path defaults to dll_config.yaml
    output_header defaults to dll_config_generated.h
"""

import os
import sys

import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DLL_DIR = SCRIPT_DIR


def read_config(config_path: str) -> dict:
    with open(config_path, 'r') as f:
        data = yaml.safe_load(f)
    return data or {}


def generate(config_path: str, output_header: str):
    data = read_config(config_path)

    circuit_controls = (data.get('advanced_parameters') or {}).get('circuitControls') or {}
    exposed = data.get('exposed_parameters') or {}

    lines = [
        "#ifndef DLL_CONFIG_GENERATED_H",
        "#define DLL_CONFIG_GENERATED_H",
        "",
        "// Auto-generated by generate_dll_config.py from " + os.path.basename(config_path),
        "// -- do not edit by hand",
        "",
        "// Advanced parameters: circuitControls current-controller tuning",
        "// (compiled in, not exposed as TB958 Parameters)",
    ]
    for name, value in circuit_controls.items():
        macro = f"CC_{name.upper()}_DEFAULT"
        lines.append(f"#define {macro} {value}")

    lines.extend([
        "",
        "// Exposed parameters: compiled-in defaults only -- the live values",
        "// come from Instance->Parameters (see gfm_battery_dll.c)",
    ])
    for name, value in exposed.items():
        macro = f"{name.upper()}_DEFAULT"
        lines.append(f"#define {macro} {value}")

    lines.append("")
    lines.append("#endif // DLL_CONFIG_GENERATED_H")
    lines.append("")

    with open(output_header, 'w') as f:
        f.write("\n".join(lines))

    print(f"Successfully generated {output_header} "
          f"({len(circuit_controls)} advanced + {len(exposed)} exposed defaults from {config_path})")


def main():
    default_config = os.path.join(DLL_DIR, 'dll_config.yaml')
    default_output = os.path.join(DLL_DIR, 'dll_config_generated.h')

    config_path = sys.argv[1] if len(sys.argv) > 1 else default_config
    output_header = sys.argv[2] if len(sys.argv) > 2 else default_output

    generate(config_path, output_header)


if __name__ == "__main__":
    main()